import { Agent, Project, Deployment, MemoryEntry, ActivityItem } from './types';

export const agents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Architect',
    role: 'System Architect',
    avatar: 'Brain',
    status: 'thinking',
    currentTask: 'Designing microservice boundaries for payment system',
    progress: 72,
    thoughtLog: [
      'Analyzing domain boundaries for payment processing',
      'Considering event-driven architecture for decoupling',
      'Mapping data flow between services',
      'Evaluating CQRS pattern for read-heavy workloads',
    ],
    color: '#06b6d4',
  },
  {
    id: 'agent-2',
    name: 'Frontend',
    role: 'Frontend Engineer',
    avatar: 'Monitor',
    status: 'working',
    currentTask: 'Building dashboard component with real-time updates',
    progress: 45,
    thoughtLog: [
      'Setting up WebSocket connection for live data',
      'Implementing optimistic UI updates',
      'Adding skeleton loaders for async content',
      'Refining component composition for reusability',
    ],
    color: '#8b5cf6',
  },
  {
    id: 'agent-3',
    name: 'Backend',
    role: 'Backend Engineer',
    avatar: 'Server',
    status: 'working',
    currentTask: 'Implementing REST API endpoints for user management',
    progress: 63,
    thoughtLog: [
      'Defining OpenAPI schema for user endpoints',
      'Implementing pagination with cursor-based approach',
      'Adding rate limiting middleware',
      'Writing validation schemas with Zod',
    ],
    color: '#06b6d4',
  },
  {
    id: 'agent-4',
    name: 'QA',
    role: 'Quality Assurance',
    avatar: 'ShieldCheck',
    status: 'reviewing',
    currentTask: 'Running integration tests on auth flow',
    progress: 88,
    thoughtLog: [
      'Generating edge case test scenarios',
      'Testing token refresh rotation logic',
      'Verifying CSRF protection headers',
      'Checking session invalidation behavior',
    ],
    color: '#8b5cf6',
  },
  {
    id: 'agent-5',
    name: 'DevOps',
    role: 'DevOps Engineer',
    avatar: 'Cloud',
    status: 'idle',
    currentTask: 'Awaiting build artifacts for deployment',
    progress: 30,
    thoughtLog: [
      'Preparing CI/CD pipeline configuration',
      'Configuring Docker multi-stage builds',
      'Setting up health check endpoints',
      'Planning zero-downtime deployment strategy',
    ],
    color: '#06b6d4',
  },
  {
    id: 'agent-6',
    name: 'Reviewer',
    role: 'Code Reviewer',
    avatar: 'Eye',
    status: 'completed',
    currentTask: 'Completed review of authentication module',
    progress: 100,
    thoughtLog: [
      'Reviewing authentication middleware implementation',
      'Checking for security vulnerabilities',
      'Verifying error handling patterns',
      'Approved with minor suggestions',
    ],
    color: '#8b5cf6',
  },
];

export const projects: Project[] = [
  {
    id: 'proj-1',
    name: 'NexusPay',
    description: 'A next-generation payment processing platform with real-time fraud detection and multi-currency support.',
    status: 'building',
    progress: 67,
    agents: ['agent-1', 'agent-2', 'agent-3'],
    createdAt: '2026-05-10T14:30:00Z',
    techStack: ['Next.js', 'TypeScript', 'PostgreSQL', 'Redis', 'Stripe'],
    files: [
      {
        id: 'file-1',
        name: 'page.tsx',
        path: '/app/dashboard/page.tsx',
        type: 'page',
        content: 'export default function DashboardPage() { ... }',
        language: 'typescript',
      },
      {
        id: 'file-2',
        name: 'PaymentForm.tsx',
        path: '/components/PaymentForm.tsx',
        type: 'component',
        content: 'export function PaymentForm() { ... }',
        language: 'typescript',
      },
      {
        id: 'file-3',
        name: 'route.ts',
        path: '/api/payments/route.ts',
        type: 'api',
        content: 'export async function POST(req: Request) { ... }',
        language: 'typescript',
      },
    ],
  },
  {
    id: 'proj-2',
    name: 'SynthOS',
    description: 'An AI-powered operating system interface with natural language commands and predictive task management.',
    status: 'generating',
    progress: 23,
    agents: ['agent-1', 'agent-4'],
    createdAt: '2026-05-13T09:15:00Z',
    techStack: ['Next.js', 'Python', 'TensorFlow', 'WebSocket', 'Docker'],
    files: [
      {
        id: 'file-4',
        name: 'CommandInterpreter.tsx',
        path: '/components/CommandInterpreter.tsx',
        type: 'component',
        content: 'export function CommandInterpreter() { ... }',
        language: 'typescript',
      },
      {
        id: 'file-5',
        name: 'TaskPredictor.py',
        path: '/ai/TaskPredictor.py',
        type: 'util',
        content: 'class TaskPredictor: ...',
        language: 'python',
      },
    ],
  },
  {
    id: 'proj-3',
    name: 'DataVault',
    description: 'Enterprise-grade data warehouse with automated ETL pipelines and real-time analytics dashboards.',
    status: 'reviewing',
    progress: 89,
    agents: ['agent-3', 'agent-4', 'agent-6'],
    createdAt: '2026-05-07T16:45:00Z',
    techStack: ['Next.js', 'TypeScript', 'Apache Kafka', 'ClickHouse', 'GraphQL'],
    files: [
      {
        id: 'file-6',
        name: 'AnalyticsDashboard.tsx',
        path: '/components/AnalyticsDashboard.tsx',
        type: 'component',
        content: 'export function AnalyticsDashboard() { ... }',
        language: 'typescript',
      },
      {
        id: 'file-7',
        name: 'etl-pipeline.ts',
        path: '/lib/etl-pipeline.ts',
        type: 'util',
        content: 'export class ETLPipeline { ... }',
        language: 'typescript',
      },
    ],
  },
  {
    id: 'proj-4',
    name: 'CloudMesh',
    description: 'Distributed cloud infrastructure management platform with auto-scaling and cost optimization.',
    status: 'deploying',
    progress: 95,
    agents: ['agent-5', 'agent-3'],
    createdAt: '2026-05-04T11:00:00Z',
    techStack: ['Next.js', 'Go', 'Kubernetes', 'Terraform', 'Prometheus'],
    files: [
      {
        id: 'file-8',
        name: 'InfrastructureMap.tsx',
        path: '/components/InfrastructureMap.tsx',
        type: 'component',
        content: 'export function InfrastructureMap() { ... }',
        language: 'typescript',
      },
      {
        id: 'file-9',
        name: 'main.go',
        path: '/api/scaler/main.go',
        type: 'api',
        content: 'func main() { ... }',
        language: 'go',
      },
    ],
  },
];

export const deployments: Deployment[] = [
  {
    id: 'deploy-1',
    projectId: 'proj-1',
    projectName: 'NexusPay',
    status: 'building',
    url: 'https://nexuspay.agentforge.dev',
    platform: 'Vercel',
    deployedAt: '2026-05-15T08:30:00Z',
    buildTime: '2m 34s',
  },
  {
    id: 'deploy-2',
    projectId: 'proj-3',
    projectName: 'DataVault',
    status: 'live',
    url: 'https://datavault.agentforge.dev',
    platform: 'AWS',
    deployedAt: '2026-05-14T22:15:00Z',
    buildTime: '4m 12s',
  },
  {
    id: 'deploy-3',
    projectId: 'proj-4',
    projectName: 'CloudMesh',
    status: 'deploying',
    url: 'https://cloudmesh.agentforge.dev',
    platform: 'GCP',
    deployedAt: '2026-05-15T10:00:00Z',
    buildTime: '3m 48s',
  },
];

export const memoryEntries: MemoryEntry[] = [
  {
    id: 'mem-1',
    type: 'architecture',
    content: 'NexusPay uses a hexagonal architecture with clear domain boundaries. Payment processing is isolated from user management through event-driven communication.',
    project: 'NexusPay',
    timestamp: '2026-05-11T14:20:00Z',
    relevance: 0.95,
  },
  {
    id: 'mem-2',
    type: 'pattern',
    content: 'All projects use the repository pattern for data access. This provides a clean abstraction layer and makes switching between ORMs straightforward.',
    project: 'Global',
    timestamp: '2026-05-09T10:30:00Z',
    relevance: 0.88,
  },
  {
    id: 'mem-3',
    type: 'bug',
    content: 'WebSocket connections drop after 30min of inactivity. Need to implement heartbeat mechanism with 25min interval to keep connections alive.',
    project: 'NexusPay',
    timestamp: '2026-05-12T16:45:00Z',
    relevance: 0.92,
  },
  {
    id: 'mem-4',
    type: 'preference',
    content: 'User prefers shadcn/ui components over custom implementations. Always check shadcn registry before building new UI components.',
    project: 'Global',
    timestamp: '2026-05-08T09:00:00Z',
    relevance: 0.85,
  },
  {
    id: 'mem-5',
    type: 'context',
    content: 'DataVault project requires compliance with SOC 2 Type II. All data handling must follow the security controls documented in the compliance spec.',
    project: 'DataVault',
    timestamp: '2026-05-10T11:15:00Z',
    relevance: 0.97,
  },
];

export const activityItems: ActivityItem[] = [
  {
    id: 'act-1',
    agent: 'Architect',
    action: 'Designed microservice boundaries for payment module',
    timestamp: '2026-05-15T10:23:00Z',
    type: 'plan',
  },
  {
    id: 'act-2',
    agent: 'Frontend',
    action: 'Implemented real-time dashboard with WebSocket integration',
    timestamp: '2026-05-15T10:18:00Z',
    type: 'code',
  },
  {
    id: 'act-3',
    agent: 'Backend',
    action: 'Created REST API endpoints for user authentication',
    timestamp: '2026-05-15T10:12:00Z',
    type: 'code',
  },
  {
    id: 'act-4',
    agent: 'QA',
    action: 'Completed integration tests for auth flow - 47/47 passing',
    timestamp: '2026-05-15T10:05:00Z',
    type: 'test',
  },
  {
    id: 'act-5',
    agent: 'Reviewer',
    action: 'Approved authentication module with minor suggestions',
    timestamp: '2026-05-15T09:58:00Z',
    type: 'review',
  },
  {
    id: 'act-6',
    agent: 'DevOps',
    action: 'Configured CI/CD pipeline with zero-downtime deployment',
    timestamp: '2026-05-15T09:45:00Z',
    type: 'deploy',
  },
  {
    id: 'act-7',
    agent: 'Architect',
    action: 'Debugged race condition in concurrent payment processing',
    timestamp: '2026-05-15T09:30:00Z',
    type: 'debug',
  },
  {
    id: 'act-8',
    agent: 'Frontend',
    action: 'Deployed preview build for stakeholder review',
    timestamp: '2026-05-15T09:15:00Z',
    type: 'deploy',
  },
];

export const terminalLines = [
  { type: 'command', text: '$ agentforge generate --project NexusPay --template saas' },
  { type: 'info', text: '[Architect] Initializing project architecture design...' },
  { type: 'info', text: '[Architect] Analyzing requirements and constraints...' },
  { type: 'agent', text: '[Architect] Selected hexagonal architecture with event-driven communication' },
  { type: 'info', text: '[Frontend] Generating component tree from architecture spec...' },
  { type: 'agent', text: '[Frontend] Created 12 components across 4 feature modules' },
  { type: 'info', text: '[Backend] Scaffolding API layer with OpenAPI specifications...' },
  { type: 'agent', text: '[Backend] Generated 8 endpoints with validation middleware' },
  { type: 'info', text: '[QA] Generating test suites from API specifications...' },
  { type: 'success', text: '[QA] 47 integration tests generated - all passing' },
  { type: 'info', text: '[DevOps] Building Docker images for 3 services...' },
  { type: 'agent', text: '[DevOps] Multi-stage builds optimized - 340MB total image size' },
  { type: 'info', text: '[Reviewer] Running automated code review...' },
  { type: 'success', text: '[Reviewer] Code quality score: 94/100 - Approved for deployment' },
];

export const featureCards = [
  {
    id: 'feat-1',
    title: 'Multi-Agent Orchestration',
    description: 'Coordinate specialized AI agents that work in parallel, each with distinct roles and expertise, to build complex systems faster.',
    icon: 'Users',
    color: '#06b6d4',
  },
  {
    id: 'feat-2',
    title: 'Autonomous Code Generation',
    description: 'Agents autonomously write, review, and refine code following architectural patterns and your project conventions.',
    icon: 'Code2',
    color: '#8b5cf6',
  },
  {
    id: 'feat-3',
    title: 'Intelligent Architecture',
    description: 'AI architects analyze requirements and generate optimal system designs with clear service boundaries and data flows.',
    icon: 'Network',
    color: '#06b6d4',
  },
  {
    id: 'feat-4',
    title: 'Self-Healing Tests',
    description: 'QA agents generate comprehensive test suites and automatically fix failing tests when implementation changes.',
    icon: 'ShieldCheck',
    color: '#8b5cf6',
  },
  {
    id: 'feat-5',
    title: 'Zero-Downtime Deploys',
    description: 'DevOps agents handle deployment pipelines with blue-green strategies, health checks, and automatic rollback capabilities.',
    icon: 'Rocket',
    color: '#06b6d4',
  },
  {
    id: 'feat-6',
    title: 'Persistent Memory',
    description: 'Agents maintain project context across sessions, remembering architecture decisions, patterns, and learned preferences.',
    icon: 'Brain',
    color: '#8b5cf6',
  },
  {
    id: 'feat-7',
    title: 'Real-Time Collaboration',
    description: 'Watch agents think, plan, and build in real-time with transparent thought logs and activity streams.',
    icon: 'Activity',
    color: '#06b6d4',
  },
  {
    id: 'feat-8',
    title: 'Adaptive Learning',
    description: 'The platform learns from your codebase and feedback, continuously improving generation quality and pattern matching.',
    icon: 'Sparkles',
    color: '#8b5cf6',
  },
];
